name: Deploy Recipes App

on:
  push:
    branches:
      - main # or your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # or your preferred Node.js version

      - name: Install dependencies
        run: npm ci # or yarn install

      - name: Build the app
        run: npm run build

      - name: Deploy to server via rsync
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.WEBGO_SFTP_HOST }}
          username: ${{ secrets.WEBGO_SFTP_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }} # Default SSH port is 22
          script: |
            # Create deployment directory if it doesn't exist
            mkdir -p /home/www/de.absolutholz.recipes
            # Rsync the build output
            rsync -avz --delete ./out/ ${{ secrets.WEBGO_SFTP_USERNAME }}@${{ secrets.WEBGO_SFTP_HOST }}:/home/www/de.absolutholz.recipes
            # Optionally restart your server (e.g., PM2, systemd)
            # ssh ${{ secrets.WEBGO_SFTP_USERNAME }}@${{ secrets.WEBGO_SFTP_HOST }} "pm2 restart your-app-name || systemctl restart your-service-name"
          #optional: if you need to execute commands before rsync
          # before_script: |
          #     ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} "mkdir -p /home/www/de.absolutholz.recipes"
